### ISSUE TITLE
Idea/request: NetriX - Bought Maps cds Reduce

### ISSUE THREAD

**Issue by MTASA-TFF** [MTASA-TFF/The-Favoured-Few#131]
Just Change DM Room bought maps cds to match that in hdm ty <3

**Comment by SkreePy18** [comment]
We are not planning to do this. As, it was a request from HDM players to reduce them in HDM arena as there are more harder maps and its more enjoyable if people could play maps they like, as for DM it is doesn't really matter because you can enjoy it or at least play it without failing in the first 30 sec.

Closed as not planned.
